version: "2.2"

services:
  backend:
    build:
      context: .
      dockerfile: src/main/java/dhbw/de/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - wetter-app

  frontend:
    build:
      context: weather-app
      dockerfile: src/Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - wetter-app

networks:
  wetter-app:
    driver: bridge
